var roster = {
'south': [
    'This Person S',
    'Stupid Student S',
    'That Person S',
    'Some Student S',
    'An Alien S',
    'Normal Person S',
    'Weird Person S',
    'Crazy Student S',
    'College Student S',
    'Drug Dealer S',
    'Depressed Student S',
    'The Queen S',
    'The King S',
],
'north': [
    'This Person N',
    'Stupid Student N',
    'That Person N',
    'Some Student N',
    'An Alien N',
    'Normal Person N',
    'Weird Person N',
    'Crazy Student N',
    'College Student N',
    'Drug Dealer N',
    'Depressed Student N',
    'The Queen N',
    'The King N',
]
}
