var roster = [
    'This Person',
    'Stupid Student',
    'That Person',
    'Some Student',
    'An Alien',
    'Normal Person',
    'Weird Person',
    'Crazy Student',
    'College Student',
    'Drug Dealer',
    'Depressed Student',
    'The Queen',
    'The King',
]
